### ISSUE TITLE
Crash 1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [SettingDust/HeraclesForBlabber#6]
https://gist.github.com/Krimatoria/010a14bbcc7e60e147d491d43b6a2651 - Log

**Comment by SettingDust** [comment]
You have no blabber?

**Comment by Krimatoria** [comment]
> You have no blabber?

Yes

**Comment by SettingDust** [comment]
> Yes

Install it. It's required

**Comment by Krimatoria** [comment]
> > Да
> 
> Установите его. Это необходимо

That's not how I answered) I already had it installed and there was a crash)

**Comment by SettingDust** [comment]
What's the version of your blabber. And full log
